# Problema 1

Las matrices $A$ y $B$ representan las ventas en dos años, en millones de dólares, de los tres productos de una empresa en las cuatro regiones en que está disponible. Es decir, $a_{ij}$ y $b_{ij}$ representan el monto de las ventas del producto $i$ en la región $j$ el primer y segundo año, respectivamente:

<br>

\begin{split}
A = \begin{pmatrix}
 2,6 &  4,8 &  1,8 & 0,9 \\
 3,2 &  4,4 &  2,5 & 2,8 \\
 2,4 &  3,6 &  3,8 & 2,5 \\
\end{pmatrix} \text{ } B= \begin{pmatrix}
 3,6 &  2,5 &  3,0 & 2,5 \\
 4,5 &  5,0 &  3,5 & 3,8 \\
 2,9 &  3,0 &  4,6 & 4,0 \\
\end{pmatrix}
\end{split}

<br>

1. Indique el orden de cada matriz.
2. Calcule la matriz $S = A + B$.
3. Calcule la matriz $D = B - A$.
4. Indique el valor e interprete los elementos $s_{24}$ y $d_{24}$.
5. Para el tercer año de funcionamiento, los tres productos ahora están disponibles en seis regiones. Durante este año, las ventas de esta empresa estarán registradas en una matriz $E$. ¿Es posible determinar la matriz $T = A + B + E$? Justifique su respuesta.

# Problema 2

Una fábrica con sucursales en Japón y China, produce tres tipos de componentes $j$, para cinco modelos de computador $i$. Los costos de producción mensual, en miles de dólares, de ambas sucursales se representan en las matrices $J$ y $C$, respectivamente:

<br>

\begin{split}
J = \begin{pmatrix}
 100 &  200 &  150  \\
 120 &  210 &  170  \\
 112 &  200 &  131  \\
 124 &  310 &  170  \\
 136 &  156 &  140  \\
\end{pmatrix} \text{ } C = \begin{pmatrix}
 110 &  190 &  160  \\
 130 &  220 &  180  \\
 146 &  190 &  141  \\
 143 &  312 &  163  \\
 137 &  116 &  156  \\
\end{pmatrix}
\end{split}

<br>

1. ¿Cuál es el orden de las matrices?
2. Inteprete el elemento $j_{21}$ y $c_{12}$ en el contexto del problema.
3. Utilizando *Python*, calcule el costo total de producción para cada modelo, considerando ambas sucursales.
4. Un trabajador indica que, en la sucursal japonesa, el costo de producción del producto $3$, modelo $4$ de computador, es más alto que en la sucursal china. ¿Tiene razón? Justifique apropiadamente.

# Problema 3

La empresa Beta tiene cinco plantas en Chile, y en cada una de ellas fabrica siete productos. El número de unidades del producto $i$ fabricadas en la planta $j$ en una semana está representado en la matriz $C$ en el elemento $c_{ij}$.

<br>

\begin{split}
C = \begin{pmatrix}
 120 &  200 &  155 &  125  &  230 \\
 155 &  130 &  110 &  160  &  180 \\
 140 &  205 &  150 &  125  &  155 \\
 130 &  120 &  230 &  225  &  125 \\
 135 &  70  &  190 &  175  &  95  \\
 110 &  265 &  180 &  230  &  180 \\
 185 &  85  &  120 &  135  &  150 \\
\end{pmatrix}
\end{split}

<br>

La empresa se expande, creando cinco plantas en Ecuador que producen los mismos siete productos. La producción semanal de esta filial estará representada por una matriz $E$.

1. Si se sabe que los volúmenes de producción semanal de la filial en Ecuador son un $20\%$ menor que en Chile, calcule la matriz $E$ utilizando *Python*.
2. Si representamos la producción semanal total de la empresa Beta, considerando ambas filiales, por la matriz $T$, escriba la expresión que calcula cada elemento de la matriz $T$ usando notación matricial.
3. Calcule la matriz $T$ utilizando *Python*.
4. Interprete los elementos $c_{34}$ y $t_{72}$ en el contexto del problema.

# Problema 4

Una empresa que fabrica zapatos tiene dos plantas, una en Valparaíso y la otra en Temuco. La empresa produce zapatos de color negro, blanco y café, tanto para niños, damas como caballeros. La capacidad actual de producción mensual (en miles de pares) para Valparaíso y Temuco, están dadas por las matrices $V$ y $T$, respectivamente. Para ambas matrices, según el orden en que se mencionan, las filas corresponden al color del calzado y las columnas al tipo de persona que utilizará el calzado.

<br>

\begin{split}
V = \begin{pmatrix}
 30 &  34 &  20  \\
 45 &  20 &  16  \\
 14 &  26 &  25  \\
\end{pmatrix} \text{ } T = \begin{pmatrix}
 35 &  30 &  26  \\
 52 &  25 &  18  \\
 23 &  24 &  32  \\
\end{pmatrix}
\end{split}

<br>

1. Determine la producción mensual total de ambas plantas, representándola en una matriz $A$. Utilice *Python* para resolver.
2. Interprete el elemento $a_{21}$ en el contexto del problema.
3. Si para el próximo año se estima que la producción en Valparaíso aumenta en un $30\%$, mientras que la de Temuco se reduce en un $10\%$, represente la nueva producción total en la matriz $B$.
4. Interprete el elemento $b_{13}$ en el contexto del problema.

In [2]:
import numpy as np
v=np.array([[30,34,20],[45,20,16],[14,26,25]])
t=np.array([[35,30,26],[52,25,18],[23,24,32]])
a=v+t
print(a)

[[65 64 46]
 [97 45 34]
 [37 50 57]]


In [3]:
a_21=a[2-1][1-1]
print(f"Se venden mensualmente {a_21} zapatos de color blanco para niños")

Se venden mensualmente 97 zapatos de color blanco para niños


In [4]:
v1=1.30*v
t1=0.90*t

B=v1+t1
print(f"para el proximo año segun el estimado en ambas plantas seria de {B}")

para el proximo año segun el estimado en ambas plantas seria de [[ 70.5  71.2  49.4]
 [105.3  48.5  37. ]
 [ 38.9  55.4  61.3]]


In [5]:
b_13=a[1-1][3-1]
print(f"Se venden mensualmente {b_13} zapatos de color negro para caballeros")

Se venden mensualmente 46 zapatos de color negro para caballeros


# Problema 5

Genere una matriz $M$ de orden $8 \times 9$ donde cada término de la matriz está definido por:

$$m_{ij} = 8i + 12j$$

y calcule su transpuesta.

In [8]:
M = np.fromfunction(lambda i, j: 8*(i+1)+12*(j+1), (8,9))
#print(M)
T = M.T
print(T)

[[ 20.  28.  36.  44.  52.  60.  68.  76.]
 [ 32.  40.  48.  56.  64.  72.  80.  88.]
 [ 44.  52.  60.  68.  76.  84.  92. 100.]
 [ 56.  64.  72.  80.  88.  96. 104. 112.]
 [ 68.  76.  84.  92. 100. 108. 116. 124.]
 [ 80.  88.  96. 104. 112. 120. 128. 136.]
 [ 92. 100. 108. 116. 124. 132. 140. 148.]
 [104. 112. 120. 128. 136. 144. 152. 160.]
 [116. 124. 132. 140. 148. 156. 164. 172.]]


# Problema 6

Genere dos matrices:

*   Una matriz $A$ de orden $5 \times 7$, con $a_{ij} = i \cdot j.$
*   Una matriz $B$ de orden $7 \times 5$, con $b_{ij} = 15i - 2j.$

y calcule $C = A^{T} + \dfrac{1}{2}B$.



In [16]:
A = np.fromfunction(lambda i, j: (i+1)*(j+1), (5,7))
print(A)
B = np.fromfunction(lambda i, j: 15*(i+1)-2*(j+1), (7,5))
print(B)


C=A.T+(1/2)*B
print(C)



[[ 1.  2.  3.  4.  5.  6.  7.]
 [ 2.  4.  6.  8. 10. 12. 14.]
 [ 3.  6.  9. 12. 15. 18. 21.]
 [ 4.  8. 12. 16. 20. 24. 28.]
 [ 5. 10. 15. 20. 25. 30. 35.]]
[[ 13.  11.   9.   7.   5.]
 [ 28.  26.  24.  22.  20.]
 [ 43.  41.  39.  37.  35.]
 [ 58.  56.  54.  52.  50.]
 [ 73.  71.  69.  67.  65.]
 [ 88.  86.  84.  82.  80.]
 [103. 101.  99.  97.  95.]]
[[ 7.5  7.5  7.5  7.5  7.5]
 [16.  17.  18.  19.  20. ]
 [24.5 26.5 28.5 30.5 32.5]
 [33.  36.  39.  42.  45. ]
 [41.5 45.5 49.5 53.5 57.5]
 [50.  55.  60.  65.  70. ]
 [58.5 64.5 70.5 76.5 82.5]]


# Problema 7

Una red de sensores recoge datos de temperatura ($°C$), humedad (porcentaje) y presión (hPa) en cinco días distintos (de lunes a viernes). Los datos medidos se muestran en la matriz $D$:

<br>

\begin{equation*}
\begin{matrix}
& \begin{matrix}
 & Lu  \ \ &Ma \ \ &Mi \ \ & Ju \ \ &Vi
\end{matrix} \\
&D = \begin{pmatrix}
20    &  28    &  22    &  26     &  24   \\
52    &  57    &  56    &  54     &  58   \\
1.066 &  1.068 &  1.066 &  1.064  &  1.068 \\
\end{pmatrix} & \ \begin{matrix}
Cº\\
\% \\
hPa
\end{matrix}\\
\end{matrix}
\end{equation*}

<br>

Se sabe que por un error de calibración de los sensores, las medidas registradas deberían ser un $5\%$ menores que las registradas.

1. Calcule en una matriz $S$ los valores correctos de temperatura, humedad y presión. Utilice *Python* para calcular.
2. Obtenga la matriz $S^{T}$.
3. Interprete los elementos $s_{24}$ y $s_{31}^{T}$.


In [24]:
D=np.array([[20,28,22,26,24],[52,57,56,54,58],[1066,1068,1066,1064,1068]])
S=0.95*D
print(S)
T=D.T
print(T)
S_24=S[2-1][4-1]
print(f"Porcentaje de humedad en dia jueves de {S_24}")
T_31=T[3-1][1-1]
print(f"Dia miercoles, grados celcius {T_31}")

[[  19.     26.6    20.9    24.7    22.8 ]
 [  49.4    54.15   53.2    51.3    55.1 ]
 [1012.7  1014.6  1012.7  1010.8  1014.6 ]]
[[  20   52 1066]
 [  28   57 1068]
 [  22   56 1066]
 [  26   54 1064]
 [  24   58 1068]]
Porcentaje de humedad en dia jueves de 51.3
Dia miercoles, grados celcius 22


# Problema 8

Una empresa tecnológica vende software y hardware en tres productos: $P_{1}$, $P_{2}$ y $P_{3}$, en cuatro zonas de la capital: norte, sur, este y oeste. Las ventas del mes, en millones de pesos, están registradas en las matrices $S$ y $H$, para software y hardware respectivamente.

<br>

\begin{split}
S = \begin{pmatrix}
 260 &  480 &  180  &  90  \\
 320 &  440 &  250  &  280 \\
 240 &  360 &  380  &  250  \\
\end{pmatrix} \text{ } H = \begin{pmatrix}
 360 &  250 &  300  &  250  \\
 450 &  500 &  350  &  380 \\
 290 &  300 &  460  &  400  \\
\end{pmatrix}
\end{split}

<br>

1. Calcule en la matriz $T$, del total de ventas de la empresa tecnológica.
2. Un trabajador indica que este mes, la sucursal de la zona sur recaudó más por la venta hardware que software, ¿es correcta su afirmación?
3. Debido al black friday se espera que el siguiente mes, las ventas de software aumenten un $7\%$ y las de hardware aumenten un $3\%$ respecto al mes actual. Encuentra en total de ventas esperadas para el siguiente mes y almacénalo en la matriz $M$. Utiliza *Python* para realizar los cálculos.
4. Interpreta los elementos $t_{24}$ y $m_{31}$ en el contexto del problema.
5. Calcula la matriz $M^{T}$ e interpreta el elemento $m_{41}^{T}$ en el contexto del problema.


In [32]:
S=np.array([[260,480,180,90],[320,440,250,280],[240,360,380,250]])
H=np.array([[360,250,300,250],[450,500,350,380],[290,300,460,400]])
T1=S+H
print(T1)
suma_S=np.sum(S,axis=0)
print(suma_S)
suma_H=np.sum(H,axis=0)
print(suma_H)
print("No recauda mas por la venta de hardware ya que de software llega los 1280 y de hardware a los 1050")
SB=1.07*S
HB=1.03*H
M=SB+HB
print(f"Cantidad de ventas de software y hardware en el mes del black friday {M}")
T_24=T1[2-1][4-1]
M_31=M[3-1][1-1]
print(f"Producto 2 vendido por planta oeste de la capital seria de {T_24}")
print(f"Producto 3 (software y hardware) vendido por la planta del norte de la capital en el mes del black friday seria de {M_31}")
MT=M.T
print(MT)
M_41=MT[4-1][1-1]
print(f"producto 1 vendido en el mes de black friday (software y hardware) en la planta del oeste seria de {M_41}")

[[620 730 480 340]
 [770 940 600 660]
 [530 660 840 650]]
[ 820 1280  810  620]
[1100 1050 1110 1030]
No recauda mas por la venta de hardware ya que de software llega los 1280 y de hardware a los 1050
Cantidad de ventas de software y hardware en el mes del black friday [[649.  771.1 501.6 353.8]
 [805.9 985.8 628.  691. ]
 [555.5 694.2 880.4 679.5]]
Producto 2 vendido por planta oeste de la capital seria de 660
Producto 3 (software y hardware) vendido por la planta del norte de la capital en el mes del black friday seria de 555.5
[[649.  805.9 555.5]
 [771.1 985.8 694.2]
 [501.6 628.  880.4]
 [353.8 691.  679.5]]
producto 1 vendido en el mes de black friday (software y hardware) en la planta del oeste seria de 353.8
