# Problema 1

La fábrica de bicicletas Expend produce dos modelos de bicicletas, $M$ y $N$. La matriz $A$ nos indica las cantidades de acero y aluminio que requiere cada bicicleta, expresadas en kg según el modelo a producir, mientras que la matriz $B$ nos entrega un reporte de la cantidad de bicicletas producidas de ambos modelos para los dos primeros meses del año pasado.

<br>

\begin{equation*}
\begin{matrix}
& \begin{matrix}
 & \ \ \ \  M & N
\end{matrix}  \\
&A= \begin{pmatrix}
1 & 2 \\
3 & 2 \\
\end{pmatrix} & \ \begin{matrix}
Acero\\
Aluminio
\end{matrix}\\
\end{matrix}
\ \ \ \ \ \ \ \ \ \ \ \ \ \
\begin{matrix}
& \begin{matrix}
& \ \ \ \ \ \ \ ene & feb &
\end{matrix} & \\
&B= \begin{pmatrix}
290 &  312 \\
 345 &  413 \\
\end{pmatrix} & \begin{matrix}
M\\
N
\end{matrix}\\
\end{matrix}
\end{equation*}

<br>

1. Indique el orden de cada matriz. ¿Es posible determinar la multiplicación entre ambas matrices? Justifique.
2. Determine utilizando *Python* la matriz $C = A \cdot B$
3. Indique e interprete el valor de los elementos $c_{21}$ y $c_{11}$.

In [ ]:
import numpy as np
A=np.array([[1,2],[3,2]])
B=np.array([[290,312],[345,413]])
#1
print("el orden seria A 2x2 y B 2x2, por lo cual si es posible mutiplicar ambas matrices")
#2
C = np.dot(A, B)
print(C)
#3
C21=C[2-1,1-1]
C11=C[1-1,1-1]
print(f"total de aluminio en el mes de enero para ambos modelos de bicicletas {C21}")
print(f"total de acero en el mes de enero para ambos modelos de bicicletas {C11}")

el orden seria A 2x2 y B 2x2, por lo cual si es posible mutiplicar ambas matrices
[[ 980 1138]
 [1560 1762]]
total de aluminio en el mes de enero para ambas bicicletas 1560
total de acero en el mes de enero para ambas bicicletas 980


# Problema 2

Una pequeña cadena tiene restaurantes de comida rápida en Santiago, Concepción y Antofagasta, en los que vende hamburguesas, completos y mateadas. En un fin de semana, las cantidades de cada comida según cada sucursal se distribuyeron de acuerdo con la siguiente matriz $V$, donde las filas corresponden a los productos y las columnas a las sucursales, mientras que los precios, en pesos, de cada producto están expresados en la matriz $P$.

<br>

\begin{split}
V &= \begin{pmatrix}
 1300 &  900  &  800  \\
 2100 &  1700 &  1500 \\
 1500 &  1200 &  900  \\
\end{pmatrix}\\
\\
P &= \begin{pmatrix}
 4200 &  1500 & 3200 \\
\end{pmatrix}
\end{split}

<br>

Si $I = P \cdot V$

1. Indique el orden de cada matriz.
2. Determine utilizando *Python* la matriz $I$.
3. Indique e interprete el valor de los elementos $v_{32}$, $p_{12}$ e $i_{13}$.

In [19]:
v=np.array([[1300,900,800],[2100,1700,1500],[1500,1200,900]])
p=np.array([[4200,1500,3200]])
#orden v 3x3 p 1x3
I = np.dot(p, v)
print(I)
#v filas restaurantes
#v columnas comida
#p filas precio
#p columnas comida

v32=v[3-1,2-1]
p12=p[1-1,2-1]
I13=I[1-1,3-1]
print(f"Cantidad de malteadas en concepcion {v32}")
print(f"precio por completos {p12} pesos")

[[13410000 10170000  8490000]]
Cantidad de malteadas en concepcion 1200
precio por completos 1500 pesos


# Problema 3

Una fábrica, para un mismo tipo de artículo eléctrico produce $2$ modelos, $A$ y $B$. Las filas de la matriz $M$, en el orden mencionado, nos muestran la cantidad de transistores y resistores que se requieren por cada artículo, según cada modelo. Por otra parte, las filas de la matriz $Q$ nos reportan las cantidades producidas de cada modelo para las tres primeras semanas del mes pasado.

<br>

\begin{split}
M = \begin{pmatrix}
 9 &  14 \\
 4 &  5  \\
\end{pmatrix} \ \ \ \ \ \ \ \ Q = \begin{pmatrix}
 200 &  240 & 220 \\
 175 &  210 & 215 \\
\end{pmatrix}
\end{split}

<br>

Además, considere las matrices $G = M \cdot Q$ y $H = Q \cdot M$.

1. Indique el orden de $M$ y $Q$.
2. ¿Es posible calcular las matrices $G$ y $H$? Justifique.
3. Determine utilizando *Python* la matriz $G$ e interprete los elementos $g_{23}$  y $g_{12}$.
4. ¿Cuántos resistores se utilizaron durante las tres semanas?

In [14]:
#M = fila 1 transitores #columna 1 modelo a
    #fila 2 resitores #columna 2 modelo b

# filas cantidades producidas modelo a y b
# columnas 3 semanas de cantidad del modelo a y b
import numpy as np
M=np.array([[9,14],[4,5]])
Q=np.array([[200,240,220],[175,210,215]])

print("M = 2x2 y Q=2x3")

print("si porque la cantidad de columas (M) es igual a la cantidad de las filas (Q)")
# H = Q2X3 * M2X2
print("no se podria realizar Q2x3 * m2x2 ya que la cantidad de columas Q no es igual a la cantidad de filas de M")

#3 calcular matriz G
G = M.dot(Q)
print(f"la matriz G \nG=n{G}")

#4
G23=G[2-1,3-1] #fila 2: resistores, columa 3: semana 3
print(f"La cantidad de resistores utilizados en la semana 3 entre ambos modelos {G23}")
G12=G[1-1,2-1] #fila 1 transistores, columa 2: semana 2
print(f"La cantidad de transistores utilizados en la semana 2 entre ambos modelos {G12}")

suma_gf=np.sum(G,axis=1)
#print(suma_gf)
print(f"La cantidad de resistores utilizados durante las tres semanas seria de {suma_gf[1]}")


M = 2x2 y Q=2x3
si porque la cantidad de columas (M) es igual a la cantidad de las filas (Q)
no se podria realizar Q2x3 * m2x2 ya que la cantidad de columas Q no es igual a la cantidad de filas de M
la matriz G 
G=n[[4250 5100 4990]
 [1675 2010 1955]]
La cantidad de resistores utilizados en la semana 3 entre ambos modelos 1955
La cantidad de transistores utilizados en la semana 2 entre ambos modelos 5100
La cantidad de resistores utilizados durante las tres semanas seria de 5640


# Problema 4

Una empresa de telecomunicaciones necesita optimizar la distribución de su infraestructura de red en Iquique, Santiago y Concepción. Las columnas de la matriz $R$, en el orden mencionado, representan la cantidad de routers y switches que se deben instalar en cada ciudad. La matriz $C$ muestra el costo de instalación, en pesos, de cada router y switch.

<br>

\begin{split}
R = \begin{pmatrix}
 50 &  70 \\
 80 &  110  \\
 60 &  90  \\
\end{pmatrix} \ \ \ \ \ \ C = \begin{pmatrix}
 80000 \\
 45000 \\
\end{pmatrix}
\end{split}

<br>

1. Calcula utilizando *Python* el costo total de instalación para cada ciudad y almacénalo en la matriz $T$.
2. ¿Cuál es la ciudad que tiene mayor costo de instalación?
3. Si se aplica un descuento del $10\%$ en el costo de instalación de los switches, calcula el nuevo costo total de instalación para cada ciudad.

# Problema 5

Una empresa de servicios en la nube distribuye datos entre tres *Data Center*. La matriz $D$ muestra el volumen de datos (en terabytes) almacenados en cada *Data Center* durante los tres primeros meses del año. Mientras que la matriz $C$ muestra los costos (en dólares) de almacenamiento por terabyte en cada *Data Center*.

<br>

\begin{equation*}
\begin{matrix}
& \begin{matrix}
& \ \ \ \ \ \ \ DC_{1} &   DC_{2} & DC_{3}&
\end{matrix} & \\
&D = \begin{pmatrix}
100 & 150 & 200 \\
120 & 180 & 220 \\
140 & 210 & 250
\end{pmatrix} & \begin{matrix}
Ene\\
Feb\\
Mar
\end{matrix}
\end{matrix}
\ \ \ \ \ \ \ \ \ \ \ \ \ \
\begin{matrix}
& \begin{matrix}
\   
\end{matrix} & \\
&C = \begin{pmatrix}
50 \\
40 \\
30
\end{pmatrix}  \begin{matrix}
DC_{1}\\
DC_{2}\\
DC_{3}
\end{matrix}\\
\end{matrix}
\end{equation*}

<br>

1. Calcula utilizando *Python* la matriz $T = D \cdot C$.
2. Un trabajador indica que en febrero el costo por almacenamiento fue el más alto, ¿es cierta su afirmación?
3. Debido a la inflación, el costo de almacenamiento por terabyte aumenta en un $2,3\%$. Calcula el nuevo costo total de almacenamiento por mes e interprete cada uno de los elementos de la nueva matriz.

In [2]:
import numpy as np
D=np.array([[100,150,200],[120,180,220],[140,210,250]])
C=np.array([[50],[40],[30]])

T = np.dot(D, C)
#print(T)

#falso el costo mas alto en almacenamiento fue en marzo

N=T*1.023
print(N)
#costo de almacenamiento subido en un 2,3% en cada mes de todos los data centers

[[17391. ]
 [20255.4]
 [23426.7]]


# Problema 6

Una compañía que fabrica un determinado producto, tiene $4$ plantas de producción y $5$ bodegas de almacenamiento. La matriz $T$ muestra las unidades de este producto que se generan mensualmente en la planta $i$ y que son transportadas a la bodega $j$, para quedar almacenadas allí durante el mes en que fueron producidas.

Además, la matriz $C$ detalla, para el primer semestre del presente año, el costo unitario (en dólares) de almacenamiento del producto durante el mes $j$ en la bodega $i$.

<br>

\begin{split}
T = \begin{pmatrix}
 500 &  400  &  300 & 200 & 100 \\
 600 &  500  &  400 & 300 & 200 \\
 700 &  600  &  500 & 400 & 300 \\
 800 &  700  &  600 & 500 & 400 \\
\end{pmatrix} \ \ \ \ \ \ C = \begin{pmatrix}
 5 &  6  &  7 &  8  &  9 & 6 \\
 4 &  5  &  6 &  7  &  8 & 7 \\
 3 &  4  &  5 &  6  &  7 & 9 \\
 2 &  3  &  4 &  5  &  6 & 6 \\
 8 &  5  &  6 &  3  &  7 & 5 \\
\end{pmatrix}
\end{split}

<br>

1. Determina la matriz $G = T \cdot C$.
2. Interpreta los elementos $t_{14}$, $c_{53}$ y $g_{35}$.
3. ¿Cuánto cuesta almacenar una unidad del producto en la bodega $4$ durante marzo de este año?
4. ¿Cuánto dinero gasta la empresa por almacenar la producción mensual de la planta $2$ durante el mes de abril?


In [ ]:
T=np.array([[500,400,300,200,100],[600,500,400,300,200],[700,600,500,400,300],[800,700,600,500,400]])
C=np.array([[5,6,7,8,9,6],[4,5,6,7,8,7],[3,4,5,6,7,9],[2,3,4,5,6,6],[8,5,6,3,7,5]])
#T i = planta j = bodega  
#C i = mes j = bodega
#G i = planta j = mes
G = np.dot(T, C)
print(G)

T14=T[1-1,4-1]
print(f"cantidad de producto generado en la primera planta de produccion y mandado almacenar en la 4ta bodega de almacenamiento es de {T14}")
C53=C[5-1,3-1]
print(f"Costo unitario del producto el mes 3 en la bodega 5 seria de {C53}")
G35=G[3-1,5-1]
print(f"Precio del producto producido por la planta nuemro 3 en el mes 5 en todas las bodegas de {G35} dolares")

#3


[[ 6200  7300  8800  9900 11700 10200]
 [ 8400  9600 11600 12800 15400 13500]
 [10600 11900 14400 15700 19100 16800]
 [12800 14200 17200 18600 22800 20100]]
cantidad de producto generado en la primera planta de produccion y mandado almacenar en la 4ta bodega de almacenamiento es de 200
Costo unitario del producto el mes 3 en la bodega 5 seria de 6
Precio del producto producido por la planta nuemro 3 en el mes 5 en todas las bodegas de 19100 dolares
La cantidad de almacenar un prodcuto en la boega 4 durante el mes de marzo es de 29000
La cantidad de almacenar un prodcuto en la boega 2 durante el mes de abril es de 66600


# Problema 7

Una empresa dedicada al desarrollo de software, que cuenta con tres sucuersales, necesita renovar los siguientes implementos para su personal: laptop de alto rendimiento, monitor externo de alta resolución, teclado mecánico, mouse ergonómico y disco duro de alta capacidad. Para esto, decide cotizar con tres proveedores y así encontrar el precio más conveniente para realizar la compra. La matriz $F$, en el orden mencionado, indica la cantidad de artículos que necesita comprar para cada sucursal. La matriz $G$ indica el precio unitario (en miles de pesos) de cada producto por proveedor.

<br>

\begin{split}
F = \begin{pmatrix}
 7 &  6  &  15 & 17 & 18 \\
 5 &  10  &  20 & 13 & 12 \\
 8 &  4  &  12 & 18 & 9 \\
\end{pmatrix} \ \ \ \ \ \ G = \begin{pmatrix}
 1700 &  1750 &  1800 \\
  868 &  803  &  840  \\
  165 &  160  &  150  \\
  70  &  73  &   65   \\
  110 &  124  &  115  \\
\end{pmatrix}
\end{split}

<br>

1. Calcula utilizando *Python* la matriz $D = F \cdot G$.
2. Interpreta los elementos $d_{33}$ y $d_{21}$.
3. ¿Cuál es el proveedor más conveniente para realizar todas las compras?
4. Si escoge el proveedor más conveniente, ¿en qué sucursal deberá invertir más dinero por la renovación de los implementos?

In [ ]:
F=np.array([[7,6,15,17,18],[5,10,20,13,12],[8,4,12,18,9]])
G=np.array([[1700,1750,1800],[868,803,840],[165,160,150],[70,73,65],[110,124,115]])
#F i = sucursales j = productos
#G i = productos j = precio unitario por proveedor
#D i = sucursales j = precio unitario por proveedor (de todos los productos)
D=np.dot(F,G)
print(D)
D33=D[3-1,3-1]
D21=D[2-1,1-1]
print(f"Sucursal 3 y los precios ofrecidos por el 3er proovedor por cada producto de {D33} mil")
print(f"Sucursal 2 y los precios ofrecidos por el 1er proovedor por cada producto de {D21} mil")

suma_D=np.sum(D,axis=0)
print(suma_D)
print(f"El proveedor mas conviente seria el numero uno con un precio de {suma_D[1]}")

print("deberia de invertir mas dinero en la sucursar 1 y con el proveedor 1")



[[22753 22941 23065]
 [22710 22417 22625]
 [21302 21562 21765]]
Sucursal 3 y los precios ofrecidos por el 3er proovedor por cada producto de 21765 mil
Sucursal 2 y los precios ofrecidos por el 1er proovedor por cada producto de 22710 mil
[66765 66920 67455]
El proveedor mas conviente seria el numero uno con un precio de 66920
deberia de invertir mas dinero en la sucursar 3 y con el proveedor 1


# Problema 8

Sea la matriz $A$:

<br>

\begin{split}
A = \begin{pmatrix}
 3 &  1  &  2 \\
 1 &  2  &  1 \\
 4 &  1  &  3 \\
\end{pmatrix}
\end{split}

<br>

1. Calcula, utilizando *Python*, la matriz $A^{-1}$.
2. Calcula la matriz $I = A \cdot A^{-1}$.
3. Calcula la matriz $I^{-1}$. Analiza este resultado, comparando con los resultados obtenidos en los ítems anteriores. ¿Puedes encontrar alguna relación para estas matrices?

In [ ]:
A=np.array([[3,1,2],[1,2,1],[4,1,3]])
A_inv = np.linalg.inv(A)
print(A_inv)

I=np.round(np.dot(A,A_inv),10)
print(I)
I_inv= np.linalg.inv(I)
print(I_inv)
#cualquier matris calculado por la misma matris con su inversa, da como resultado su identidad y cualquier matriz multiplicado por la identidad, da como resultado la misma matriz

[[ 2.5 -0.5 -1.5]
 [ 0.5  0.5 -0.5]
 [-3.5  0.5  2.5]]
[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Problema 9

1. Considera que el siguiente sistema de ecuaciones:

<br>

\begin{split}
2x + y & = 7 \\
3x - 2y & = 21
\end{split}

<br>

$\hspace{1cm}$ Se puede escribir matricialmente como:

<br>

\begin{split}
\begin{pmatrix}
 2  &  1 \\
 3 & -2 \\
\end{pmatrix} \cdot \begin{pmatrix}
 x \\
 y \\
\end{pmatrix} = \begin{pmatrix}
 7 \\
 21 \\
\end{pmatrix}
\end{split}

<br>

* Utiliza la matriz inversa para encontrar los valores de $x$ e $y$ que permiten satisfacer ambas ecuaciones simultáneamente.

<br>

2. Considera que el siguiente sistema de ecuaciones:

<br>

\begin{split}
h + m & = 60 \\
0,16h + 0,2m & = 11
\end{split}

<br>

$\hspace{1cm}$ Se puede escribir matricialmente como:

<br>

\begin{split}
\begin{pmatrix}
 1  &  1 \\
 0,16 & 0,2 \\
\end{pmatrix} \cdot \begin{pmatrix}
 h \\
 m \\
\end{pmatrix} = \begin{pmatrix}
 60 \\
 11 \\
\end{pmatrix}
\end{split}

<br>

* Utiliza la matriz inversa para encontrar los valores de $h$ y $m$ que permiten satisfacer el sistema de ecuaciones.

In [11]:
A=np.array([[2,1],[3,-2]])
B=np.array([[7],[21]])

A_inv=np.linalg.inv(A)

X=np.round(np.dot(A_inv,B),10)
print(X)

B1=np.round(np.dot(A,X),10)
print(B1)

[[ 5.]
 [-3.]]
[[ 7.]
 [21.]]


In [12]:
A=np.array([[1,1],[0.16,0.2]])
B=np.array([[60],[11]])
A_inv=np.linalg.inv(A)
X=np.round(np.dot(A_inv,B),10)
print(X)
B1=np.round(np.dot(A,X),10)
print(B1)

[[25.]
 [35.]]
[[60.]
 [11.]]


# Problema 10

Considera los siguientes sistemas de ecuaciones:

<br>

**a)**
\begin{split}
2m + 4p & = 2900 \\
3m + 3p & = 3150
\end{split}
<br>
<br>
**b)**
\begin{split}
n + v & = 160 \\
50n + 300v & = 23000
\end{split}

<br>

1. Escribe ambos sistemas de ecuaciones de forma matricial.
1. Utiliza la matriz inversa para calcular las soluciones de ambos sistemas de ecuaciones.




# Problema 11

Una persona tiene $\$8000$ en monedas de $\$10$ y de $50$. El sistema de ecuaciones que representa la situación es el siguiente:

<br>

\begin{split}
x + y & = 200 \\
10x + 50y & = 8000
\end{split}

<br>

1. ¿Qué representa cada variable?
2. Explica qué representa cada una de las ecuaciones del sistema.
3. ¿Cuántas monedas de $\$10$ y de $\$50$ tiene?

# Problema 12

En una granja hay $132$ animales entre patos y vacas. En total hay $402$ patas. El sistema que modela la situación planteada es:

<br>

\begin{split}
p + v & = 132 \\
2p + 4v & = 402
\end{split}

<br>

1. ¿Qué representan las incógnitas del sistema?
2. ¿Cuántos patos hay?

# Problema 13

Luis compró $5$ cables USB y $6$ pendrives, en total canceló $\$82.890$. Pablo compró a los mismos precios $3$ cables USB y $7$ pendrives, y canceló $\$59.900$.

El sistema que modela el problema es:

<br>

\begin{split}
5x + 6y &= 82890 \\
3x +  7y &= 59900
\end{split}

<br>


1. ¿Qué representa cada incógnita en el contexto del problema?
2. Determina cuánto pagaron por cada cable USB.